language: java

install:
    - mvn clean install -DskipTests

branches:
  only:
    - master
    - release
    - qa
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/

services:
  hello-world:
    docker_image:
      dockerfile: Dockerfile
      path: .
      name: registry2.swarm.devfactory.com/optiva/sao/test-image

jenkins:
  platform: docker
  sudo: sudo
  stash:
    allowEmpty: true
    name: 'artifacts'
  pipeline_jenkinsfile: aurea-central-jervis/pipelines/SaaS
  collect:
    artifacts: ./target/*.jar