language: java

install:
    - mvn clean install -DskipTests

branches:
  only:
    - master
    - release
    - qa
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/

jenkins:
#  platform: docker
#  sudo: sudo
  stash:
    allowEmpty: true
    name: 'artifacts'
  pipeline_jenkinsfile: aurea-central-jervis/pipelines/SaaSMultiPlatform
  collect:
    artifacts: 'target/*.jar'

services:
  saotest:
    docker_image:
      dockerfile: Dockerfile
      path: .
      name: registry2.swarm.devfactory.com/optiva/sao/test-image


notifications:
  email:
    recipients:
      - to: emin.sadiyev@optiva.com
        on_success: always
        on_failure: always